pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn eclipse:eclipse -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn eclipse:eclipse clean test'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
